### PR TITLE
Fix some CSS bugs

### PR DESCRIPTION
**Pull request by LeshaKoss**

### CODE REVIEW

**Comment by kossnocorp** [comment]
@LeshaKoss please show me some proofs (screenshots before/after or steps to reproduce) for every fix. I've tried to reproduce but with no luck.

**Comment by LeshaKoss** [comment]
@kossnocorp sure. Hold on, 8 screen size PNGs ahead

**Fix search field style 9a96fda02809fdecf80e5e7337114957834bc3f1**
screen shot 2016-03-20 at 08 30 07
screen shot 2016-03-20 at 08 30 36

**Comment by LeshaKoss** [comment]
**Fix getting started style 9fc502cd959af250716776d636b6b19c4f886a53**

screen shot 2016-03-20 at 08 31 45
screen shot 2016-03-20 at 08 31 22

**Comment by LeshaKoss** [comment]
**Fix docs list style 18b0e5d4643e56c7e46ffa1f0d21ea6bb5277f34**
screen shot 2016-03-20 at 08 33 35
screen shot 2016-03-20 at 08 34 00

**Comment by LeshaKoss** [comment]
**Fix promo overflow style 2952ac396ae30d50a928bf9e99ce869b5a5a8402**
screen shot 2016-03-20 at 08 35 11
screen shot 2016-03-20 at 08 34 39

@kossnocorp that's all. Didn't check if they reproduce in other browsers

**Comment by LeshaKoss** [comment]
@kossnocorp sorry for undescriptive commit messages 😬

**Comment by kossnocorp** [comment]
@LeshaKoss good catches :+1: :clapper:

**Pull request merged**
